CXX = g++

CXXFLAGS = -Wall -g

TARGET = my_program

OBJ = main.o autobot.o decepticon.o otherTest.o animalbot.o team.o transformer.o transformerTest.o union.o
$(TARGET): $(OBJ)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJ)

transformer.o: Transformer.cpp Transformer.h
	$(CXX) $(CXXFLAGS) -c Transformer.cpp

main.o: main.cpp Transformer.h
	$(CXX) $(CXXFLAGS) -c main.cpp

decepticon.o: Decepticon.cpp Decepticon.h
	$(CXX) $(CXXFLAGS) -c Decepticon.cpp

autobot.o: Autobot.cpp Autobot.h
	$(CXX) $(CXXFLAGS) -c Autobot.cpp

animalbot.o: Animalbot.cpp Animalbot.h
	$(CXX) $(CXXFLAGS) -c Animalbot.cpp

team.o: Team.cpp Team.h
	$(CXX) $(CXXFLAGS) -c Team.cpp
union.o: Union.cpp Union.h
	$(CXX) $(CXXFLAGS) -c Union.cpp

otherTest.o: OtherTest.cpp Decepticon.h Autobot.h Team.h Animalbot.h Union.h
	$(CXX) $(CXXFLAGS) -c OtherTest.cpp

transformerTest.o: TransformerTest.cpp Transformer.h 
	$(CXX) $(CXXFLAGS) -c TransformerTest.cpp


clean:
	rm -f $(OBJ) $(TARGET)